using ClusterVR.CreatorKit.Item.Implements;
using UnityEditor;
using UnityEngine;


namespace Ponta.CCK_Generator
{

    public static class HandGunCreator
    {
        [MenuItem("CCK_Generator/Create/New HandGun")]
        public static void CreateHandGunPrefab() {

            GameObjectCreator gameObjectCreator = new GameObjectCreator();
            HandGunDefinition handGunDefinition = new HandGunDefinition();

            var result = gameObjectCreator.Init(handGunDefinition);
            if (!result) { return; }

            gameObjectCreator.AddItem(handGunDefinition.itemInfo);
            gameObjectCreator.SaveAsPrefabAsset();
        }

    }

    public class HandGunDefinition : BaseDefinition
    {
        public ItemInfo itemInfo = new ItemInfo();


        public HandGunDefinition() {

            OutputPath = "HandGun.prefab";
            PrototypePath = "Prototype_HandGun.prefab";

            /* Define Item  */
            itemInfo.isItem = true;
            itemInfo.itemName = "ハンドガン";

            itemInfo.isMovableItem = true;

            itemInfo.isGrabbableItem = true;
        }

    }

    public class BaseDefinition
    {
        const string AutoGeneratedPrefabsPath = "Assets/CCK_Generator/AutoGeneratedPrefabs/";
        const string PrototypePrefabsPath = "Assets/CCK_Generator/PrototypePrefabs/";

        protected string OutputPath { get; set; }

        protected string PrototypePath { get; set; }


        public string GetOutputPath() {
            return AutoGeneratedPrefabsPath + OutputPath;
        }

        public string GetPrototypePath() {
            return PrototypePrefabsPath + PrototypePath;
        }

    }


}

