using ClusterVR.CreatorKit.Item.Implements;
using UnityEditor;
using UnityEngine;


namespace Ponta.CCK_Generator
{

    public static class HandGunCreator
    {
        [MenuItem("CCK_Generator/Create/New HandGun")]
        public static void CreateHandGunPrefab() {

            GameObjectCreator gameObjectCreator = new GameObjectCreator();
            HandGunDefinition handGunDefinition = new HandGunDefinition();

            gameObjectCreator.Init(handGunDefinition);
            gameObjectCreator.AddItem(handGunDefinition.itemInfo);
            gameObjectCreator.SaveAsPrefabAsset();
        }

    }

    
    public class HandGunDefinition
    {
        public string outputPath { get; } = "Assets/CCK_Generator/AutoGeneratedPrefabs/HandGun.prefab";

        public string prototypePath { get; } = "Assets/CCK_Generator/PrototypePrefabs/HandGun.prefab";

        public ItemInfo itemInfo = new ItemInfo();

        public HandGunDefinition() {

            itemInfo.isItem = true;
            itemInfo.itemName = "ハンドガン";

            itemInfo.isMovableItem = true;

            itemInfo.isGrabbableItem = true;
        }

    }

    

}

