

namespace Ponta.CCK_Generator.Base
{

    public class BaseDefinition
    {
        const string AutoGeneratedPrefabsPath = "Assets/CCK_Generator/AutoGeneratedPrefabs/";
        const string PrototypePrefabsPath = "Assets/CCK_Generator/PrototypePrefabs/";

        protected string OutputPath { get; set; }

        protected string PrototypePath { get; set; }


        public string GetOutputPath() {
            return AutoGeneratedPrefabsPath + OutputPath;
        }

        public string GetPrototypePath() {
            return PrototypePrefabsPath + PrototypePath;
        }

    }

}