

namespace Ponta.CCK_Generator.Base
{

    public class PrefabsPathController
    {
        const string AutoGeneratedPrefabsPath = "Assets/CCK_Generator/AutoGeneratedPrefabs/";
        const string PrototypePrefabsPath = "Assets/CCK_Generator/PrototypePrefabs/";

        public string OutputPath;

        public string PrototypePath;


        public string GetOutputPath() {
            return AutoGeneratedPrefabsPath + OutputPath;
        }

        public string GetPrototypePath() {
            return PrototypePrefabsPath + PrototypePath;
        }

    }

}