#if UNITY_EDITOR


namespace Ponta.CCK_Generator.Base
{

    public class PrefabsPathController
    {
        const string AutoGeneratedPrefabsPath = "Assets/CCK_Generator/AutoGeneratedPrefabs/";
        const string PrototypePrefabsPath = "Assets/CCK_Generator/PrototypePrefabs/";

        string prototypePath;

        string outputPath;


        public void SetPath(string prototypePath, string outputPath) {
            this.prototypePath = prototypePath;
            this.outputPath = outputPath;
        }

        public string GetPrototypePath() {
            return PrototypePrefabsPath + prototypePath;
        }

        public string GetOutputPath() {
            return AutoGeneratedPrefabsPath + outputPath;
        }

    }

}
#endif
